# -*- mode: python ; coding: utf-8 -*-
# LabManager.spec - PyInstaller spec for server app (app-test.py)

a = Analysis(
    ['app-test.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('firebase_key.json', '.'),
        ('ads.json', '.'),
        ('background.jpg', '.'),
    ],
    hiddenimports=[
        'flask',
        'flask_sqlalchemy',
        'flask_cors',
        'sqlalchemy',
        'sqlalchemy.dialects.postgresql',
        'psycopg2',
        'werkzeug',
        'werkzeug.security',
        'werkzeug.utils',
        'openpyxl',
        'openpyxl.styles',
        'pandas',
        'requests',
        'importlib',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='LabManager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['myicon.ico'],
    uac_admin=True,
)
